"""Create initial restaurant management schema.

Revision ID: 20260721_0001
Revises:
Create Date: 2026-07-21
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260721_0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all initial application tables."""

    op.create_table(
        "restaurant_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "restaurant_name",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("gstin", sa.String(length=30), nullable=True),
        sa.Column(
            "default_gst_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "invoice_prefix",
            sa.String(length=10),
            nullable=False,
        ),
        sa.Column(
            "receipt_footer",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "logo_path",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "timezone",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_gst_percentage >= 0",
            name=op.f(
                "ck_restaurant_settings_"
                "default_gst_percentage_non_negative"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_restaurant_settings"),
        ),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "firebase_uid",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "full_name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_users"),
        ),
        sa.UniqueConstraint(
            "email",
            name=op.f("uq_users_email"),
        ),
        sa.UniqueConstraint(
            "firebase_uid",
            name=op.f("uq_users_firebase_uid"),
        ),
    )

    op.create_index(
        "ix_users_is_active",
        "users",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_users_role",
        "users",
        ["role"],
        unique=False,
    )

    op.create_table(
        "dining_tables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "table_number",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "area",
            sa.String(length=80),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "capacity > 0",
            name=op.f("ck_dining_tables_capacity_positive"),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_dining_tables"),
        ),
        sa.UniqueConstraint(
            "table_number",
            name=op.f("uq_dining_tables_table_number"),
        ),
    )

    op.create_index(
        "ix_dining_tables_area",
        "dining_tables",
        ["area"],
        unique=False,
    )
    op.create_index(
        "ix_dining_tables_is_active",
        "dining_tables",
        ["is_active"],
        unique=False,
    )

    op.create_table(
        "menu_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "display_order >= 0",
            name=op.f(
                "ck_menu_categories_display_order_non_negative"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_menu_categories"),
        ),
        sa.UniqueConstraint(
            "name",
            name=op.f("uq_menu_categories_name"),
        ),
    )

    op.create_index(
        "ix_menu_categories_display_order",
        "menu_categories",
        ["display_order"],
        unique=False,
    )
    op.create_index(
        "ix_menu_categories_is_active",
        "menu_categories",
        ["is_active"],
        unique=False,
    )

    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "full_name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "phone",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_customers_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_customers"),
        ),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("uq_customers_user_id"),
        ),
    )

    op.create_index(
        "ix_customers_email",
        "customers",
        ["email"],
        unique=False,
    )
    op.create_index(
        "ix_customers_is_active",
        "customers",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_customers_phone",
        "customers",
        ["phone"],
        unique=False,
    )

    op.create_table(
        "menu_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "category_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "price",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "food_type",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "image_path",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "is_available",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price > 0",
            name=op.f("ck_menu_items_price_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["menu_categories.id"],
            name=op.f(
                "fk_menu_items_category_id_menu_categories"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_menu_items"),
        ),
        sa.UniqueConstraint(
            "category_id",
            "name",
            name="uq_menu_items_category_name",
        ),
    )

    op.create_index(
        "ix_menu_items_category_id",
        "menu_items",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        "ix_menu_items_food_type",
        "menu_items",
        ["food_type"],
        unique=False,
    )
    op.create_index(
        "ix_menu_items_is_active",
        "menu_items",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_menu_items_is_available",
        "menu_items",
        ["is_available"],
        unique=False,
    )
    op.create_index(
        "ix_menu_items_name",
        "menu_items",
        ["name"],
        unique=False,
    )

    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "reservation_number",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "customer_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "table_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "created_by_user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "start_time",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "end_time",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "guest_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "cancellation_reason",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "cancelled_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_time > start_time",
            name=op.f(
                "ck_reservations_end_time_after_start_time"
            ),
        ),
        sa.CheckConstraint(
            "guest_count > 0",
            name=op.f(
                "ck_reservations_guest_count_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f(
                "fk_reservations_created_by_user_id_users"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f(
                "fk_reservations_customer_id_customers"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["dining_tables.id"],
            name=op.f(
                "fk_reservations_table_id_dining_tables"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_reservations"),
        ),
        sa.UniqueConstraint(
            "reservation_number",
            name=op.f(
                "uq_reservations_reservation_number"
            ),
        ),
    )

    op.create_index(
        "ix_reservations_customer_id",
        "reservations",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_reservations_customer_start",
        "reservations",
        ["customer_id", "start_time"],
        unique=False,
    )
    op.create_index(
        "ix_reservations_end_time",
        "reservations",
        ["end_time"],
        unique=False,
    )
    op.create_index(
        "ix_reservations_start_time",
        "reservations",
        ["start_time"],
        unique=False,
    )
    op.create_index(
        "ix_reservations_status",
        "reservations",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_reservations_table_id",
        "reservations",
        ["table_id"],
        unique=False,
    )
    op.create_index(
        "ix_reservations_table_time",
        "reservations",
        ["table_id", "start_time", "end_time"],
        unique=False,
    )

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "order_number",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "customer_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "table_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "reservation_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "created_by_user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "order_type",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "special_instructions",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "delivery_address",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "cancelled_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "cancellation_reason",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f(
                "fk_orders_created_by_user_id_users"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_orders_customer_id_customers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f(
                "fk_orders_reservation_id_reservations"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["dining_tables.id"],
            name=op.f(
                "fk_orders_table_id_dining_tables"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_orders"),
        ),
        sa.UniqueConstraint(
            "order_number",
            name=op.f("uq_orders_order_number"),
        ),
        sa.UniqueConstraint(
            "reservation_id",
            name=op.f("uq_orders_reservation_id"),
        ),
    )

    op.create_index(
        "ix_orders_created_at",
        "orders",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_orders_created_by_user_id",
        "orders",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_orders_customer_id",
        "orders",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_orders_order_type",
        "orders",
        ["order_type"],
        unique=False,
    )
    op.create_index(
        "ix_orders_status",
        "orders",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_orders_table_id",
        "orders",
        ["table_id"],
        unique=False,
    )
    op.create_index(
        "ix_orders_table_status",
        "orders",
        ["table_id", "status"],
        unique=False,
    )

    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "order_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "menu_item_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "item_name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "special_instruction",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "line_total",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "line_total >= 0",
            name=op.f(
                "ck_order_items_line_total_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=op.f(
                "ck_order_items_quantity_positive"
            ),
        ),
        sa.CheckConstraint(
            "unit_price > 0",
            name=op.f(
                "ck_order_items_unit_price_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
            name=op.f(
                "fk_order_items_menu_item_id_menu_items"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f(
                "fk_order_items_order_id_orders"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_order_items"),
        ),
    )

    op.create_index(
        "ix_order_items_menu_item_id",
        "order_items",
        ["menu_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_order_items_order_id",
        "order_items",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        "ix_order_items_order_menu_item",
        "order_items",
        ["order_id", "menu_item_id"],
        unique=False,
    )

    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "order_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "invoice_number",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "discount_type",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "discount_value",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "gst_percentage",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "gst_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "grand_total",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.String(length=20),
            nullable=True,
        ),
        sa.Column(
            "payment_status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "paid_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "refunded_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "refund_reason",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_amount >= 0",
            name=op.f(
                "ck_invoices_discount_amount_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "discount_value >= 0",
            name=op.f(
                "ck_invoices_discount_value_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "grand_total >= 0",
            name=op.f(
                "ck_invoices_grand_total_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "gst_amount >= 0",
            name=op.f(
                "ck_invoices_gst_amount_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "gst_percentage >= 0",
            name=op.f(
                "ck_invoices_gst_percentage_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "subtotal >= 0",
            name=op.f(
                "ck_invoices_subtotal_non_negative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f(
                "fk_invoices_order_id_orders"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_invoices"),
        ),
        sa.UniqueConstraint(
            "invoice_number",
            name=op.f(
                "uq_invoices_invoice_number"
            ),
        ),
        sa.UniqueConstraint(
            "order_id",
            name=op.f("uq_invoices_order_id"),
        ),
    )

    op.create_index(
        "ix_invoices_created_at",
        "invoices",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_paid_at",
        "invoices",
        ["paid_at"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_payment_method",
        "invoices",
        ["payment_method"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_payment_status",
        "invoices",
        ["payment_status"],
        unique=False,
    )


def downgrade() -> None:
    """Remove all initial application tables."""

    op.drop_index(
        "ix_invoices_payment_status",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_payment_method",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_paid_at",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_created_at",
        table_name="invoices",
    )
    op.drop_table("invoices")

    op.drop_index(
        "ix_order_items_order_menu_item",
        table_name="order_items",
    )
    op.drop_index(
        "ix_order_items_order_id",
        table_name="order_items",
    )
    op.drop_index(
        "ix_order_items_menu_item_id",
        table_name="order_items",
    )
    op.drop_table("order_items")

    op.drop_index(
        "ix_orders_table_status",
        table_name="orders",
    )
    op.drop_index(
        "ix_orders_table_id",
        table_name="orders",
    )
    op.drop_index(
        "ix_orders_status",
        table_name="orders",
    )
    op.drop_index(
        "ix_orders_order_type",
        table_name="orders",
    )
    op.drop_index(
        "ix_orders_customer_id",
        table_name="orders",
    )
    op.drop_index(
        "ix_orders_created_by_user_id",
        table_name="orders",
    )
    op.drop_index(
        "ix_orders_created_at",
        table_name="orders",
    )
    op.drop_table("orders")

    op.drop_index(
        "ix_reservations_table_time",
        table_name="reservations",
    )
    op.drop_index(
        "ix_reservations_table_id",
        table_name="reservations",
    )
    op.drop_index(
        "ix_reservations_status",
        table_name="reservations",
    )
    op.drop_index(
        "ix_reservations_start_time",
        table_name="reservations",
    )
    op.drop_index(
        "ix_reservations_end_time",
        table_name="reservations",
    )
    op.drop_index(
        "ix_reservations_customer_start",
        table_name="reservations",
    )
    op.drop_index(
        "ix_reservations_customer_id",
        table_name="reservations",
    )
    op.drop_table("reservations")

    op.drop_index(
        "ix_menu_items_name",
        table_name="menu_items",
    )
    op.drop_index(
        "ix_menu_items_is_available",
        table_name="menu_items",
    )
    op.drop_index(
        "ix_menu_items_is_active",
        table_name="menu_items",
    )
    op.drop_index(
        "ix_menu_items_food_type",
        table_name="menu_items",
    )
    op.drop_index(
        "ix_menu_items_category_id",
        table_name="menu_items",
    )
    op.drop_table("menu_items")

    op.drop_index(
        "ix_customers_phone",
        table_name="customers",
    )
    op.drop_index(
        "ix_customers_is_active",
        table_name="customers",
    )
    op.drop_index(
        "ix_customers_email",
        table_name="customers",
    )
    op.drop_table("customers")

    op.drop_index(
        "ix_menu_categories_is_active",
        table_name="menu_categories",
    )
    op.drop_index(
        "ix_menu_categories_display_order",
        table_name="menu_categories",
    )
    op.drop_table("menu_categories")

    op.drop_index(
        "ix_dining_tables_is_active",
        table_name="dining_tables",
    )
    op.drop_index(
        "ix_dining_tables_area",
        table_name="dining_tables",
    )
    op.drop_table("dining_tables")

    op.drop_index(
        "ix_users_role",
        table_name="users",
    )
    op.drop_index(
        "ix_users_is_active",
        table_name="users",
    )
    op.drop_table("users")

    op.drop_table("restaurant_settings")